version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: ./php/Dockerfile
    image: php:8.2-fpm-custom
    container_name: php_app
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    restart: always
    depends_on:
      - db
    networks:
      ecp_req_network:
        ipv4_address: 192.168.30.2

  web:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "80:80"
    volumes:
      - web_data:/var/www/html
      - ./src:/var/www/html
      - ./default.conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./default.conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      ecp_req_network:
        ipv4_address: 192.168.30.3
    depends_on:
      - app
    restart: always

  mariadb:
    image: mariadb:latest
    restart: unless-stopped
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: adminecp
      MYSQL_DATABASE: ecp_req
      MYSQL_USER: admin
      MYSQL_PASSWORD: ecp
    networks:
      ecp_req_network:
        ipv4_address: 192.168.30.4
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: mariadb  # เชื่อมกับชื่อ service mariadb
      MYSQL_ROOT_PASSWORD: adminecp
    depends_on:
      - mariadb
    networks:
      ecp_req_network:
        ipv4_address: 192.168.30.5

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/app
    working_dir: /app
    command: ["composer", "install", "--no-interaction"]
    networks:
      ecp_req_network:
        ipv4_address: 192.168.30.6

networks:
  ecp_req_network:
    driver: bridge
    ipam:
      config:
        - subnet: 192.168.30.0/24

volumes:
  db_data:
  web_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/www/html'
