version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: php:8.2-fpm-custom
    container_name: php_app
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-network
    restart: always
    depends_on:
      - db

  web:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "80:80"
    volumes:
      - web_data:/var/www/html
      - ./src:/var/www/html
      - ./default.conf/default.conf:/etc/nginx/conf.d/default.conf
      - ./default.conf/nginx.conf:/etc/nginx/nginx.conf
    networks:
      - app-network
    depends_on:
      - app
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: ecp_req
      MYSQL_ROOT_PASSWORD: adminecp
      MYSQL_USER: ecp
      MYSQL_PASSWORD: ecp123456700
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: adminecp
    depends_on:
      - db
    networks:
      - app-network

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/app
    working_dir: /app
    command: ["composer", "install", "--no-interaction"]
    networks:
      - app-network

volumes:
  db_data:
  web_data:
    driver: local
    driver_opts:
      type: 'none'
      o: 'bind'
      device: '/var/www/html'
networks:
  app-network:
    driver: bridge
