version: '3.8'

services:
  app:
    image: php:8.2-fpm
    container_name: php_app
    volumes:
      - ./src:/var/www/html
    working_dir: /var/www/html
    networks:
      - app-network
    restart: always
    depends_on:
      - db

  web:
    image: nginx:latest
    container_name: nginx_web
    ports:
      - "80:80"
    volumes:
      - ./src:/var/www/html
      - ./default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_DATABASE: your_db_name
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_USER: your_user
      MYSQL_PASSWORD: your_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: your_root_password
    depends_on:
      - db
    networks:
      - app-network

  composer:
    image: composer:latest
    container_name: composer
    volumes:
      - ./src:/app
    working_dir: /app
    command: ["composer", "install", "--no-interaction"]
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge
